window.comparisonMeta = {
  "title": "원챗 150개 비교표",
  "sections": [
    "1-50 핵심 운영",
    "51-100 품질·승인·보안",
    "101-150 성장·자동화·확장"
  ]
};

window.comparisonData = [
  {
    "id": 1,
    "section": "1-50 핵심 운영",
    "feature": "멀티채널 대화 수집",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "문자·챗봇·DM·공지 반응을 하나의 이벤트 레이어로 통합하세요."
  },
  {
    "id": 2,
    "section": "1-50 핵심 운영",
    "feature": "채팅/이메일/음성 통합 보기",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "초기에는 문자·챗·공지 중심으로 가고, 이후 음성·메일을 붙이는 편이 좋습니다."
  },
  {
    "id": 3,
    "section": "1-50 핵심 운영",
    "feature": "신규 대화 자동 생성 트리거",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "강",
    "onechat": "강",
    "priority": "차별",
    "suggestion": "링크 클릭 후 즉시 대화 시작은 원챗의 대표 강점이므로 업종별 진입 플로우를 더 세분화하세요."
  },
  {
    "id": 4,
    "section": "1-50 핵심 운영",
    "feature": "고객 유형별 진입 제어",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "강",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "유입경로·고객등급·캠페인 기준으로 진입 시나리오를 분기하세요."
  },
  {
    "id": 5,
    "section": "1-50 핵심 운영",
    "feature": "세그먼트 기반 진입 제한",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "강",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "누가 어떤 챗봇 시나리오에 들어오는지 세그먼트 룰을 별도로 두세요."
  },
  {
    "id": 6,
    "section": "1-50 핵심 운영",
    "feature": "운영자 통합 작업공간",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "강",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "대화·공지·승인·분석을 한 화면에서 보는 운영자 홈이 최우선입니다."
  },
  {
    "id": 7,
    "section": "1-50 핵심 운영",
    "feature": "대화 상태 추적",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "강",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "새로 들어옴, AI처리중, 승인대기, 사람대응, 보류, 종료 상태를 명확히 나누세요."
  },
  {
    "id": 8,
    "section": "1-50 핵심 운영",
    "feature": "미응답/미해결 큐",
    "salesforce": "중",
    "zendesk": "강",
    "intercom": "강",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "사람이 지금 봐야 할 대화만 모아주는 큐를 반드시 만드세요."
  },
  {
    "id": 9,
    "section": "1-50 핵심 운영",
    "feature": "미진입 고객 탐지",
    "salesforce": "약",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "중",
    "priority": "차별",
    "suggestion": "문자를 받았지만 챗봇에 안 들어온 고객 추적은 원챗의 전환관리 핵심입니다."
  },
  {
    "id": 10,
    "section": "1-50 핵심 운영",
    "feature": "전환 퍼널 통계",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "강",
    "priority": "필수",
    "suggestion": "발송-클릭-대화-상담-계약까지 끊기지 않는 퍼널을 대시보드 1순위로 두세요."
  },
  {
    "id": 11,
    "section": "1-50 핵심 운영",
    "feature": "지식기반 응답",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "강",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "문서·운영지침·상담사례를 구조화된 지식베이스로 묶으세요."
  },
  {
    "id": 12,
    "section": "1-50 핵심 운영",
    "feature": "AI 답변 제안",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "강",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "운영자용 답변 초안 기능은 응답 속도와 품질을 동시에 올립니다."
  },
  {
    "id": 13,
    "section": "1-50 핵심 운영",
    "feature": "상담원 보조 AI",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "강",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "고객용 AI와 별개로 운영자 코파일럿을 분리해 두세요."
  },
  {
    "id": 14,
    "section": "1-50 핵심 운영",
    "feature": "고객용 AI와 운영자용 AI 분리",
    "salesforce": "중",
    "zendesk": "강",
    "intercom": "강",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "고객 응대 AI와 운영자 분석 AI를 분리해야 운영 품질이 안정됩니다."
  },
  {
    "id": 15,
    "section": "1-50 핵심 운영",
    "feature": "브랜드 톤/행동 지침 반영",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "강",
    "onechat": "강",
    "priority": "차별",
    "suggestion": "원챗은 '운영자를 닮은 AI' 포지션을 더 강하게 밀 수 있습니다."
  },
  {
    "id": 16,
    "section": "1-50 핵심 운영",
    "feature": "구조화된 절차 실행",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "강",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "질문 유형별 SOP를 만들고 AI가 절차대로 처리하게 하세요."
  },
  {
    "id": 17,
    "section": "1-50 핵심 운영",
    "feature": "외부 시스템 연결형 절차",
    "salesforce": "중",
    "zendesk": "약",
    "intercom": "강",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "핵심 운영판이 완성된 뒤 예약·CRM·결제 연동으로 확장하세요."
  },
  {
    "id": 18,
    "section": "1-50 핵심 운영",
    "feature": "예시 기반 학습",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "강",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "좋은 답변 예시와 나쁜 답변 예시를 모두 학습 자산으로 축적하세요."
  },
  {
    "id": 19,
    "section": "1-50 핵심 운영",
    "feature": "민감한 답변 제어",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "환불·분쟁·금전·의료성 표현은 자동승인 금지 규칙을 두세요."
  },
  {
    "id": 20,
    "section": "1-50 핵심 운영",
    "feature": "다국어 지원",
    "salesforce": "중",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "국내 집중 단계에서는 낮은 우선순위로 두고 나중에 확장하세요."
  },
  {
    "id": 21,
    "section": "1-50 핵심 운영",
    "feature": "의도(Intent) 분류",
    "salesforce": "중",
    "zendesk": "강",
    "intercom": "약",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "질문을 의도별로 자동 분류해야 대량 운영이 가능합니다."
  },
  {
    "id": 22,
    "section": "1-50 핵심 운영",
    "feature": "감정(Sentiment) 분류",
    "salesforce": "약",
    "zendesk": "강",
    "intercom": "약",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "불만·불안·호감 태깅이 있어야 운영자가 먼저 볼 고객을 선별할 수 있습니다."
  },
  {
    "id": 23,
    "section": "1-50 핵심 운영",
    "feature": "언어(Language) 분류",
    "salesforce": "약",
    "zendesk": "강",
    "intercom": "약",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "국내 고객 위주라면 추후 확장 항목으로 두어도 됩니다."
  },
  {
    "id": 24,
    "section": "1-50 핵심 운영",
    "feature": "긴급도 분류",
    "salesforce": "강",
    "zendesk": "중",
    "intercom": "약",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "긴급·중요·고가치·일반 문의 구분은 승인 큐와 직접 연결하세요."
  },
  {
    "id": 25,
    "section": "1-50 핵심 운영",
    "feature": "고객 가치 분류",
    "salesforce": "중",
    "zendesk": "약",
    "intercom": "약",
    "onechat": "갭",
    "priority": "차별",
    "suggestion": "잠재고객 가치 점수화는 원챗이 영업형 시장에서 강해지는 핵심 포인트입니다."
  },
  {
    "id": 26,
    "section": "1-50 핵심 운영",
    "feature": "주제별 분기 처리",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "강",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "예약·가격·환불·후기·제휴·불만 등 주제별 다른 경로가 필요합니다."
  },
  {
    "id": 27,
    "section": "1-50 핵심 운영",
    "feature": "운영 큐 자동 생성",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "승인대기·직접통화 권장·불만관리·VIP응대 큐를 자동으로 뽑아주세요."
  },
  {
    "id": 28,
    "section": "1-50 핵심 운영",
    "feature": "스킬 기반 라우팅",
    "salesforce": "강",
    "zendesk": "약",
    "intercom": "약",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "운영자 1명 기준일 때는 낮은 우선순위, 팀 확장 시 도입하세요."
  },
  {
    "id": 29,
    "section": "1-50 핵심 운영",
    "feature": "업무량 기반 라우팅",
    "salesforce": "강",
    "zendesk": "약",
    "intercom": "약",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "조직형 확장 단계에 더 필요한 기능입니다."
  },
  {
    "id": 30,
    "section": "1-50 핵심 운영",
    "feature": "사람 이관 규칙",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "강",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "어떤 조건에서 AI가 멈추고 사람이 들어오는지 규칙을 명확히 정의하세요."
  },
  {
    "id": 31,
    "section": "1-50 핵심 운영",
    "feature": "AI→사람 핸드오프",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "강",
    "onechat": "강",
    "priority": "차별",
    "suggestion": "원챗은 ‘운영자를 닮은 AI → 실제 운영자’ 흐름으로 브랜딩할 수 있습니다."
  },
  {
    "id": 32,
    "section": "1-50 핵심 운영",
    "feature": "추가 정보 수집 후 이관",
    "salesforce": "중",
    "zendesk": "약",
    "intercom": "강",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "사람이 보기 전에 핵심질문·감정·요약을 먼저 수집해야 합니다."
  },
  {
    "id": 33,
    "section": "1-50 핵심 운영",
    "feature": "승인 요청 단계",
    "salesforce": "강",
    "zendesk": "약",
    "intercom": "중",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "AI 즉시 실행과 운영자 승인 요청을 분리하면 운영 체계가 선명해집니다."
  },
  {
    "id": 34,
    "section": "1-50 핵심 운영",
    "feature": "승인 없이 자동 실행",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "강",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "저위험·반복 문의는 자동 실행해 운영자는 예외만 보게 하세요."
  },
  {
    "id": 35,
    "section": "1-50 핵심 운영",
    "feature": "보류 상태 관리",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "보류 사유와 재검토 시점을 함께 관리해야 합니다."
  },
  {
    "id": 36,
    "section": "1-50 핵심 운영",
    "feature": "직접 통화/미팅 권장 분류",
    "salesforce": "중",
    "zendesk": "약",
    "intercom": "약",
    "onechat": "갭",
    "priority": "차별",
    "suggestion": "‘직접 만나야 할 고객’을 시스템이 뽑아주는 기능은 영업형 시장에서 매우 강합니다."
  },
  {
    "id": 37,
    "section": "1-50 핵심 운영",
    "feature": "민감 액션 승인 프로세스",
    "salesforce": "강",
    "zendesk": "약",
    "intercom": "약",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "환불·보상·제휴·의료성 메시지는 승인 프로세스를 거치게 하세요."
  },
  {
    "id": 38,
    "section": "1-50 핵심 운영",
    "feature": "운영자 지침 재실행",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "운영자가 A/B/C 유형별로 지침을 내리면 AI가 대량 실행하도록 설계하세요."
  },
  {
    "id": 39,
    "section": "1-50 핵심 운영",
    "feature": "운영자 지침 히스토리",
    "salesforce": "중",
    "zendesk": "약",
    "intercom": "약",
    "onechat": "갭",
    "priority": "차별",
    "suggestion": "운영자의 지침 기록은 원챗만의 운영 노하우 DB가 됩니다."
  },
  {
    "id": 40,
    "section": "1-50 핵심 운영",
    "feature": "사람 대응 후 보고 자동화",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "약",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "사람이 해결한 건도 AI가 요약·태깅·재활용 후보로 정리해야 합니다."
  },
  {
    "id": 41,
    "section": "1-50 핵심 운영",
    "feature": "해결률/미해결률 대시보드",
    "salesforce": "중",
    "zendesk": "강",
    "intercom": "강",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "AI가 스스로 끝낸 비율과 사람이 개입한 비율을 분리해서 보여주세요."
  },
  {
    "id": 42,
    "section": "1-50 핵심 운영",
    "feature": "대화 단위 리포트",
    "salesforce": "중",
    "zendesk": "강",
    "intercom": "강",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "대화별 결과 요약, 감정, 전환 여부를 리포트 단위로 남기세요."
  },
  {
    "id": 43,
    "section": "1-50 핵심 운영",
    "feature": "주제 탐색기",
    "salesforce": "약",
    "zendesk": "중",
    "intercom": "강",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "이번 주 급증한 질문·전환 높은 주제를 자동으로 보여줘야 합니다."
  },
  {
    "id": 44,
    "section": "1-50 핵심 운영",
    "feature": "검색어/질문 패턴 분석",
    "salesforce": "약",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "갭",
    "priority": "차별",
    "suggestion": "실제 고객 질문을 분석하면 마케팅 문구와 세일즈 스크립트가 더 강해집니다."
  },
  {
    "id": 45,
    "section": "1-50 핵심 운영",
    "feature": "에스컬레이션 분석",
    "salesforce": "중",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "왜 사람이 개입했는지 유형화하면 AI 약점을 바로 볼 수 있습니다."
  },
  {
    "id": 46,
    "section": "1-50 핵심 운영",
    "feature": "품질 점수화(QA)",
    "salesforce": "약",
    "zendesk": "강",
    "intercom": "약",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "AI 답변 품질을 수동·자동으로 점수화해야 운영 품질이 흔들리지 않습니다."
  },
  {
    "id": 47,
    "section": "1-50 핵심 운영",
    "feature": "수동/자동 리뷰 병행",
    "salesforce": "약",
    "zendesk": "강",
    "intercom": "약",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "중요 대화는 사람 리뷰, 일반 대화는 자동 리뷰로 나누세요."
  },
  {
    "id": 48,
    "section": "1-50 핵심 운영",
    "feature": "테스트/프리뷰 환경",
    "salesforce": "중",
    "zendesk": "약",
    "intercom": "강",
    "onechat": "약",
    "priority": "차별",
    "suggestion": "운영자가 발송 전 직접 체험하는 프리뷰는 현장 신뢰도를 크게 높입니다."
  },
  {
    "id": 49,
    "section": "1-50 핵심 운영",
    "feature": "운영 개선 추천",
    "salesforce": "중",
    "zendesk": "강",
    "intercom": "강",
    "onechat": "갭",
    "priority": "차별",
    "suggestion": "대시보드가 ‘이렇게 바꾸면 어떨까요’까지 제안하는 순간 가치가 커집니다."
  },
  {
    "id": 50,
    "section": "1-50 핵심 운영",
    "feature": "통합 실행 대시보드",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "강",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "숫자판 + 승인판 + 이슈판 + 실행판 + 전략판이 합쳐진 통합 운영 대시보드로 가야 합니다."
  },
  {
    "id": 51,
    "section": "51-100 품질·승인·보안",
    "feature": "권한 기반 메뉴 노출",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "운영자·매니저·상담원·분석가별로 보는 화면을 나눠야 합니다."
  },
  {
    "id": 52,
    "section": "51-100 품질·승인·보안",
    "feature": "역할 기반 접근 제어(RBAC)",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "대규모 운영 전에는 권한 체계가 반드시 필요합니다."
  },
  {
    "id": 53,
    "section": "51-100 품질·승인·보안",
    "feature": "승인권자 지정",
    "salesforce": "강",
    "zendesk": "중",
    "intercom": "약",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "메시지 승인권자와 예외 승인권자를 구분하세요."
  },
  {
    "id": 54,
    "section": "51-100 품질·승인·보안",
    "feature": "지식문서 승인 워크플로",
    "salesforce": "강",
    "zendesk": "중",
    "intercom": "약",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "운영 지침과 FAQ 수정은 승인 후 반영되게 하세요."
  },
  {
    "id": 55,
    "section": "51-100 품질·승인·보안",
    "feature": "프롬프트 버전관리",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "어떤 프롬프트 버전이 어떤 성과를 냈는지 추적해야 합니다."
  },
  {
    "id": 56,
    "section": "51-100 품질·승인·보안",
    "feature": "프롬프트 롤백",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "실패한 프롬프트를 즉시 이전 버전으로 되돌릴 수 있어야 합니다."
  },
  {
    "id": 57,
    "section": "51-100 품질·승인·보안",
    "feature": "시나리오 버전관리",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "강",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "시나리오 변경 이력과 성과를 연결해서 봐야 합니다."
  },
  {
    "id": 58,
    "section": "51-100 품질·승인·보안",
    "feature": "메시지 템플릿 버전관리",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "공지/후속 템플릿도 버전과 반응률을 추적하세요."
  },
  {
    "id": 59,
    "section": "51-100 품질·승인·보안",
    "feature": "배포 전 승인 체크리스트",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "약",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "대량 발송 전 톤, 법적 리스크, 대상군, 예외조건 점검이 필요합니다."
  },
  {
    "id": 60,
    "section": "51-100 품질·승인·보안",
    "feature": "배포 일정 예약",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "강",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "세그먼트별 예약 발송은 운영 효율을 크게 높입니다."
  },
  {
    "id": 61,
    "section": "51-100 품질·승인·보안",
    "feature": "A/B 테스트",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "약",
    "priority": "차별",
    "suggestion": "문구/톤/CTA를 실험해 전환 좋은 패턴을 찾으세요."
  },
  {
    "id": 62,
    "section": "51-100 품질·승인·보안",
    "feature": "멀티암드 밴딧 최적화",
    "salesforce": "약",
    "zendesk": "약",
    "intercom": "약",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "초기에는 A/B 테스트로 충분하고, 이후 자동 최적화로 확장하세요."
  },
  {
    "id": 63,
    "section": "51-100 품질·승인·보안",
    "feature": "클릭률/응답률 비교",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "문자-챗봇-공지 반응을 같은 기준으로 비교해야 합니다."
  },
  {
    "id": 64,
    "section": "51-100 품질·승인·보안",
    "feature": "전환 기여도 분석",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "갭",
    "priority": "차별",
    "suggestion": "어떤 질문과 어떤 응답이 계약으로 이어졌는지 역추적해야 합니다."
  },
  {
    "id": 65,
    "section": "51-100 품질·승인·보안",
    "feature": "고객 여정 타임라인",
    "salesforce": "강",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "문자 수신부터 계약까지를 하나의 타임라인으로 보게 하세요."
  },
  {
    "id": 66,
    "section": "51-100 품질·승인·보안",
    "feature": "오퍼/이벤트별 성과 분석",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "이벤트별 유입·대화·전환을 따로 관리하세요."
  },
  {
    "id": 67,
    "section": "51-100 품질·승인·보안",
    "feature": "세그먼트 성과 비교",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "연령, 유입경로, 관심사, 반응온도별 성과를 비교해야 합니다."
  },
  {
    "id": 68,
    "section": "51-100 품질·승인·보안",
    "feature": "응답 지연 시간 분석",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "AI/사람 응답시간을 분리해 SLA 관점으로 보세요."
  },
  {
    "id": 69,
    "section": "51-100 품질·승인·보안",
    "feature": "운영자 개입 빈도 분석",
    "salesforce": "중",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "AI가 못 푸는 영역을 파악하는 핵심 지표입니다."
  },
  {
    "id": 70,
    "section": "51-100 품질·승인·보안",
    "feature": "실패 응답 탐지",
    "salesforce": "중",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "엉뚱한 답변, 무응답, 회피 응답을 자동 탐지해야 합니다."
  },
  {
    "id": 71,
    "section": "51-100 품질·승인·보안",
    "feature": "환각/오답 신고 큐",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "약",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "운영자나 고객이 문제 답변을 바로 신고하고 재학습에 연결하세요."
  },
  {
    "id": 72,
    "section": "51-100 품질·승인·보안",
    "feature": "리뷰 샘플링 규칙",
    "salesforce": "중",
    "zendesk": "강",
    "intercom": "약",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "전체를 다 못 보니 고위험 대화만 자동 샘플링하세요."
  },
  {
    "id": 73,
    "section": "51-100 품질·승인·보안",
    "feature": "품질 임계값 알림",
    "salesforce": "중",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "품질 점수가 특정 기준 아래로 떨어지면 운영자에게 즉시 알리세요."
  },
  {
    "id": 74,
    "section": "51-100 품질·승인·보안",
    "feature": "고객 만족도 수집(CSAT)",
    "salesforce": "중",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "대화 종료 후 만족도 질문을 붙이면 품질 개선에 도움이 됩니다."
  },
  {
    "id": 75,
    "section": "51-100 품질·승인·보안",
    "feature": "고객 불만 경보",
    "salesforce": "중",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "불만 어휘·감정이 일정 수준 넘으면 즉시 경보를 띄우세요."
  },
  {
    "id": 76,
    "section": "51-100 품질·승인·보안",
    "feature": "민감 키워드 감지",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "환불·법적조치·욕설·피해 등 키워드는 별도 감지하세요."
  },
  {
    "id": 77,
    "section": "51-100 품질·승인·보안",
    "feature": "컴플라이언스 태그",
    "salesforce": "강",
    "zendesk": "중",
    "intercom": "약",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "업종별 주의 답변을 태그로 관리해 사고를 줄이세요."
  },
  {
    "id": 78,
    "section": "51-100 품질·승인·보안",
    "feature": "메시지 발송 금지 시간대 관리",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "야간·공휴일·수신 민감시간은 자동 회피가 필요합니다."
  },
  {
    "id": 79,
    "section": "51-100 품질·승인·보안",
    "feature": "수신거부/차단 관리",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "채널별 수신거부를 중앙에서 관리해야 합니다."
  },
  {
    "id": 80,
    "section": "51-100 품질·승인·보안",
    "feature": "개인정보 마스킹",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "전화번호·주소·민감정보는 자동 마스킹하세요."
  },
  {
    "id": 81,
    "section": "51-100 품질·승인·보안",
    "feature": "PII 탐지",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "개인정보 탐지는 원본 저장 이전 단계에서 처리하는 것이 좋습니다."
  },
  {
    "id": 82,
    "section": "51-100 품질·승인·보안",
    "feature": "감사 로그(Audit Log)",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "누가 무엇을 승인·수정·발송했는지 로그를 남기세요."
  },
  {
    "id": 83,
    "section": "51-100 품질·승인·보안",
    "feature": "세션 기록 보관 정책",
    "salesforce": "강",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "대화 보존 기간과 삭제 기준을 명확히 두세요."
  },
  {
    "id": 84,
    "section": "51-100 품질·승인·보안",
    "feature": "데이터 익명화",
    "salesforce": "강",
    "zendesk": "중",
    "intercom": "약",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "분석용 데이터는 익명화 버전으로도 활용할 수 있게 준비하세요."
  },
  {
    "id": 85,
    "section": "51-100 품질·승인·보안",
    "feature": "법적 보존(Legal Hold)",
    "salesforce": "강",
    "zendesk": "약",
    "intercom": "약",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "소송 가능성 높은 업종이면 추후 고려하세요."
  },
  {
    "id": 86,
    "section": "51-100 품질·승인·보안",
    "feature": "백업/복구 정책",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "통합 대시보드가 되려면 백업과 복구 체계가 함께 있어야 합니다."
  },
  {
    "id": 87,
    "section": "51-100 품질·승인·보안",
    "feature": "재처리 큐",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "실패한 발송, 실패한 AI 처리 건을 다시 태울 큐가 필요합니다."
  },
  {
    "id": 88,
    "section": "51-100 품질·승인·보안",
    "feature": "배치 작업 모니터링",
    "salesforce": "강",
    "zendesk": "중",
    "intercom": "약",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "대량 재분류·대량 재발송 작업의 상태를 보여주세요."
  },
  {
    "id": 89,
    "section": "51-100 품질·승인·보안",
    "feature": "대량 작업 취소/롤백",
    "salesforce": "강",
    "zendesk": "중",
    "intercom": "약",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "잘못된 대량 실행을 즉시 멈출 수 있어야 합니다."
  },
  {
    "id": 90,
    "section": "51-100 품질·승인·보안",
    "feature": "운영 알림 센터",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "지금 봐야 할 승인, 위험, 급증 이슈를 한곳에서 보여주세요."
  },
  {
    "id": 91,
    "section": "51-100 품질·승인·보안",
    "feature": "이상치 탐지",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "약",
    "priority": "차별",
    "suggestion": "반응률 급락·불만 급증·이관 급증을 자동 감지하면 강력합니다."
  },
  {
    "id": 92,
    "section": "51-100 품질·승인·보안",
    "feature": "트렌드 급증 탐지",
    "salesforce": "약",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "갭",
    "priority": "차별",
    "suggestion": "갑자기 많이 묻는 질문을 잡아 마케팅/FAQ에 바로 반영하세요."
  },
  {
    "id": 93,
    "section": "51-100 품질·승인·보안",
    "feature": "지식 공백 추천",
    "salesforce": "중",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "AI가 답 못하는 질문이 많으면 ‘새 문서 필요’를 추천하게 하세요."
  },
  {
    "id": 94,
    "section": "51-100 품질·승인·보안",
    "feature": "프롬프트 개선 추천",
    "salesforce": "중",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "갭",
    "priority": "차별",
    "suggestion": "실패 응답을 근거로 프롬프트 개선안을 제안하세요."
  },
  {
    "id": 95,
    "section": "51-100 품질·승인·보안",
    "feature": "운영자 메모/협업 코멘트",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "대화 단위로 내부 메모를 남길 수 있어야 팀 운영이 됩니다."
  },
  {
    "id": 96,
    "section": "51-100 품질·승인·보안",
    "feature": "태스크 생성",
    "salesforce": "강",
    "zendesk": "중",
    "intercom": "약",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "직접 전화, 방문, 계약서 전달 등 후속 업무를 태스크화하세요."
  },
  {
    "id": 97,
    "section": "51-100 품질·승인·보안",
    "feature": "리마인더",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "특정 고객 재접촉 시점을 자동으로 잡아주세요."
  },
  {
    "id": 98,
    "section": "51-100 품질·승인·보안",
    "feature": "캘린더 연동",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "약",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "상담 예약형 업종이면 추후 빠르게 붙일 수 있습니다."
  },
  {
    "id": 99,
    "section": "51-100 품질·승인·보안",
    "feature": "슬랙/메일 알림 연동",
    "salesforce": "강",
    "zendesk": "중",
    "intercom": "약",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "초기에는 내부 알림센터로 충분하고 이후 외부 알림으로 확장하세요."
  },
  {
    "id": 100,
    "section": "51-100 품질·승인·보안",
    "feature": "운영 보고서 자동 생성",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "갭",
    "priority": "차별",
    "suggestion": "일간·주간·월간 보고서를 자동 생성하면 경영자용 가치가 커집니다."
  },
  {
    "id": 101,
    "section": "101-150 성장·자동화·확장",
    "feature": "캠페인 관리",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "문자·챗봇·공지 전체를 캠페인 단위로 묶어 관리하세요."
  },
  {
    "id": 102,
    "section": "101-150 성장·자동화·확장",
    "feature": "캠페인별 목표 설정",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "상담예약, 가입, 결제 등 목표를 캠페인마다 다르게 두세요."
  },
  {
    "id": 103,
    "section": "101-150 성장·자동화·확장",
    "feature": "캠페인별 KPI 추적",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "목표 대비 성과를 실시간으로 추적해야 합니다."
  },
  {
    "id": 104,
    "section": "101-150 성장·자동화·확장",
    "feature": "세그먼트 자동 갱신",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "행동 변화에 따라 세그먼트가 자동으로 바뀌어야 합니다."
  },
  {
    "id": 105,
    "section": "101-150 성장·자동화·확장",
    "feature": "라이프사이클 단계 분류",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "처음 접촉-관심-상담-계약-재구매 단계로 관리하세요."
  },
  {
    "id": 106,
    "section": "101-150 성장·자동화·확장",
    "feature": "냉각/가열 점수",
    "salesforce": "약",
    "zendesk": "약",
    "intercom": "약",
    "onechat": "갭",
    "priority": "차별",
    "suggestion": "고객 반응 온도를 점수화하면 재접촉 효율이 높아집니다."
  },
  {
    "id": 107,
    "section": "101-150 성장·자동화·확장",
    "feature": "구매/계약 가능성 예측",
    "salesforce": "중",
    "zendesk": "약",
    "intercom": "약",
    "onechat": "갭",
    "priority": "차별",
    "suggestion": "영업형 시장이라면 계약 가능성 예측이 매우 강력한 기능입니다."
  },
  {
    "id": 108,
    "section": "101-150 성장·자동화·확장",
    "feature": "이탈 가능성 예측",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "약",
    "onechat": "갭",
    "priority": "차별",
    "suggestion": "관심이 식는 고객을 미리 잡아낼 수 있으면 효과가 큽니다."
  },
  {
    "id": 109,
    "section": "101-150 성장·자동화·확장",
    "feature": "재접촉 최적 시점 추천",
    "salesforce": "약",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "중",
    "priority": "차별",
    "suggestion": "AI 동행과 가장 잘 맞는 고급 기능입니다."
  },
  {
    "id": 110,
    "section": "101-150 성장·자동화·확장",
    "feature": "최적 채널 추천",
    "salesforce": "약",
    "zendesk": "약",
    "intercom": "중",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "나중에 문자/챗/DM 중 어디가 좋을지 자동 제안하도록 확장할 수 있습니다."
  },
  {
    "id": 111,
    "section": "101-150 성장·자동화·확장",
    "feature": "최적 메시지 톤 추천",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "중",
    "priority": "차별",
    "suggestion": "딱딱/친근/전문/감성 톤 중 어떤 톤이 잘 먹히는지 추천하세요."
  },
  {
    "id": 112,
    "section": "101-150 성장·자동화·확장",
    "feature": "고객군별 CTA 추천",
    "salesforce": "약",
    "zendesk": "약",
    "intercom": "약",
    "onechat": "갭",
    "priority": "차별",
    "suggestion": "유형별로 상담예약, 링크클릭, 답장유도 등 CTA를 달리 추천하세요."
  },
  {
    "id": 113,
    "section": "101-150 성장·자동화·확장",
    "feature": "콘텐츠 추천 엔진",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "운영자에게 어떤 자료를 보낼지 추천하는 기능은 후속 확장에 좋습니다."
  },
  {
    "id": 114,
    "section": "101-150 성장·자동화·확장",
    "feature": "FAQ 자동 생성",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "약",
    "priority": "차별",
    "suggestion": "많이 묻는 질문을 바탕으로 FAQ를 자동 생성하세요."
  },
  {
    "id": 115,
    "section": "101-150 성장·자동화·확장",
    "feature": "FAQ 성과 분석",
    "salesforce": "약",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "FAQ가 실제로 답변 성공률을 높였는지 보세요."
  },
  {
    "id": 116,
    "section": "101-150 성장·자동화·확장",
    "feature": "세일즈 스크립트 추천",
    "salesforce": "약",
    "zendesk": "약",
    "intercom": "약",
    "onechat": "갭",
    "priority": "차별",
    "suggestion": "영업형 업종에서 직접 통화 전 스크립트 추천은 강력한 무기입니다."
  },
  {
    "id": 117,
    "section": "101-150 성장·자동화·확장",
    "feature": "통화 요약 입력",
    "salesforce": "중",
    "zendesk": "강",
    "intercom": "약",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "사람이 직접 통화한 뒤 요약을 넣어 AI 학습에 연결해야 합니다."
  },
  {
    "id": 118,
    "section": "101-150 성장·자동화·확장",
    "feature": "미팅 요약 입력",
    "salesforce": "중",
    "zendesk": "약",
    "intercom": "약",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "오프라인 만남 결과도 시스템 안에 다시 축적하세요."
  },
  {
    "id": 119,
    "section": "101-150 성장·자동화·확장",
    "feature": "오프라인 후속 플로우",
    "salesforce": "약",
    "zendesk": "약",
    "intercom": "약",
    "onechat": "갭",
    "priority": "차별",
    "suggestion": "직접 만남 이후 후속 메시지를 자동 설계하는 기능은 차별점이 큽니다."
  },
  {
    "id": 120,
    "section": "101-150 성장·자동화·확장",
    "feature": "리퍼럴/소개 추적",
    "salesforce": "약",
    "zendesk": "약",
    "intercom": "약",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "소개 기반 업종이면 추후 붙이기 좋은 기능입니다."
  },
  {
    "id": 121,
    "section": "101-150 성장·자동화·확장",
    "feature": "브로드캐스트 세분화",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "HI 공지발송을 전체/퍼널/공유보다 더 세분화하세요."
  },
  {
    "id": 122,
    "section": "101-150 성장·자동화·확장",
    "feature": "브로드캐스트 승인 체계",
    "salesforce": "중",
    "zendesk": "약",
    "intercom": "약",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "대량 공지 전 승인과 프리뷰를 붙이세요."
  },
  {
    "id": 123,
    "section": "101-150 성장·자동화·확장",
    "feature": "브로드캐스트 피로도 관리",
    "salesforce": "약",
    "zendesk": "약",
    "intercom": "약",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "너무 자주 보내는 고객을 자동으로 눌러줘야 합니다."
  },
  {
    "id": 124,
    "section": "101-150 성장·자동화·확장",
    "feature": "빈도 캡(Frequency Capping)",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "고객별 발송 빈도를 제한해 피로감을 줄이세요."
  },
  {
    "id": 125,
    "section": "101-150 성장·자동화·확장",
    "feature": "침묵 사용자 재활성화",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "중",
    "priority": "차별",
    "suggestion": "오랫동안 반응 없는 고객을 다시 데워주는 시나리오를 강화하세요."
  },
  {
    "id": 126,
    "section": "101-150 성장·자동화·확장",
    "feature": "장기 미응답 휴면 전환",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "휴면 고객을 별도 상태로 돌려 운영 비용을 줄이세요."
  },
  {
    "id": 127,
    "section": "101-150 성장·자동화·확장",
    "feature": "휴면 복귀 캠페인",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "약",
    "priority": "차별",
    "suggestion": "휴면 고객만을 위한 복귀 메시지 전략을 두세요."
  },
  {
    "id": 128,
    "section": "101-150 성장·자동화·확장",
    "feature": "온보딩 시퀀스",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "강",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "처음 대화하는 고객에게 단계별 적응 흐름을 제공하세요."
  },
  {
    "id": 129,
    "section": "101-150 성장·자동화·확장",
    "feature": "리텐션 시퀀스",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "강",
    "onechat": "중",
    "priority": "차별",
    "suggestion": "관계 유지형 업종에서 핵심 가치가 커집니다."
  },
  {
    "id": 130,
    "section": "101-150 성장·자동화·확장",
    "feature": "업셀/크로스셀 시퀀스",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "계약 후 추가 전환 시장에서 활용도가 높습니다."
  },
  {
    "id": 131,
    "section": "101-150 성장·자동화·확장",
    "feature": "VIP 전용 시나리오",
    "salesforce": "중",
    "zendesk": "약",
    "intercom": "약",
    "onechat": "갭",
    "priority": "차별",
    "suggestion": "가치 높은 고객은 완전히 다른 운영을 하도록 분리하세요."
  },
  {
    "id": 132,
    "section": "101-150 성장·자동화·확장",
    "feature": "이슈 상황 일괄 대응",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "약",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "장애, 일정 변경, 가격정책 변경 등 이슈 대응 시나리오가 필요합니다."
  },
  {
    "id": 133,
    "section": "101-150 성장·자동화·확장",
    "feature": "긴급 공지 모드",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "약",
    "onechat": "중",
    "priority": "필수",
    "suggestion": "긴급 상황에서 어떤 순서로 누구에게 알릴지 정리해두세요."
  },
  {
    "id": 134,
    "section": "101-150 성장·자동화·확장",
    "feature": "실시간 모니터링 보드",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "지금 들어오는 대화량, 불만, 승인대기, 긴급건을 실시간으로 보여주세요."
  },
  {
    "id": 135,
    "section": "101-150 성장·자동화·확장",
    "feature": "경영자용 요약 보드",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "약",
    "priority": "차별",
    "suggestion": "운영자용과 별개로 경영자용 요약판을 두면 의사결정이 빨라집니다."
  },
  {
    "id": 136,
    "section": "101-150 성장·자동화·확장",
    "feature": "팀장용 성과 보드",
    "salesforce": "중",
    "zendesk": "강",
    "intercom": "약",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "팀 운영이 커질 때 의미가 커지는 기능입니다."
  },
  {
    "id": 137,
    "section": "101-150 성장·자동화·확장",
    "feature": "상담원 성과 비교",
    "salesforce": "중",
    "zendesk": "강",
    "intercom": "약",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "AI 중심 초기 구조에서는 후순위로 두어도 됩니다."
  },
  {
    "id": 138,
    "section": "101-150 성장·자동화·확장",
    "feature": "고객 유형별 대시보드",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "VIP, 불만, 신규, 휴면 등 유형별 보드가 필요합니다."
  },
  {
    "id": 139,
    "section": "101-150 성장·자동화·확장",
    "feature": "지점/브랜드별 대시보드",
    "salesforce": "강",
    "zendesk": "중",
    "intercom": "약",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "멀티브랜드 운영 시 확장 기능으로 좋습니다."
  },
  {
    "id": 140,
    "section": "101-150 성장·자동화·확장",
    "feature": "API 제공",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "강",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "핵심 제품 안정화 후 외부 연동용 API를 여세요."
  },
  {
    "id": 141,
    "section": "101-150 성장·자동화·확장",
    "feature": "웹훅(Webhook)",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "강",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "다른 솔루션과 이벤트 연동이 필요할 때 도입하면 됩니다."
  },
  {
    "id": 142,
    "section": "101-150 성장·자동화·확장",
    "feature": "외부 BI 연동",
    "salesforce": "강",
    "zendesk": "중",
    "intercom": "약",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "초기에는 내부 대시보드로 충분하고 이후 BI로 확장하세요."
  },
  {
    "id": 143,
    "section": "101-150 성장·자동화·확장",
    "feature": "데이터 내보내기",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "경영 보고와 추가 분석을 위해 엑셀/CSV 내보내기가 필요합니다."
  },
  {
    "id": 144,
    "section": "101-150 성장·자동화·확장",
    "feature": "데이터 가져오기",
    "salesforce": "강",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "약",
    "priority": "필수",
    "suggestion": "기존 CRM·상담 DB를 가져와 맥락 있는 운영을 가능하게 하세요."
  },
  {
    "id": 145,
    "section": "101-150 성장·자동화·확장",
    "feature": "샌드박스 환경",
    "salesforce": "중",
    "zendesk": "약",
    "intercom": "중",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "대형 고객사 도입 단계에서 중요해지는 기능입니다."
  },
  {
    "id": 146,
    "section": "101-150 성장·자동화·확장",
    "feature": "멀티테넌시",
    "salesforce": "강",
    "zendesk": "강",
    "intercom": "강",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "플랫폼형 비즈니스로 확장하면 반드시 필요합니다."
  },
  {
    "id": 147,
    "section": "101-150 성장·자동화·확장",
    "feature": "화이트라벨링",
    "salesforce": "중",
    "zendesk": "약",
    "intercom": "약",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "파트너/본부 사업 확장 시 가치가 있습니다."
  },
  {
    "id": 148,
    "section": "101-150 성장·자동화·확장",
    "feature": "파트너/본부 계정 구조",
    "salesforce": "중",
    "zendesk": "약",
    "intercom": "약",
    "onechat": "약",
    "priority": "후순위",
    "suggestion": "본부/파트너 확장 사업 구조에 맞춰 나중에 중요해질 수 있습니다."
  },
  {
    "id": 149,
    "section": "101-150 성장·자동화·확장",
    "feature": "운영 정책 엔진",
    "salesforce": "강",
    "zendesk": "중",
    "intercom": "강",
    "onechat": "갭",
    "priority": "필수",
    "suggestion": "승인·보류·직접대응·자동실행 규칙을 정책 엔진으로 관리하세요."
  },
  {
    "id": 150,
    "section": "101-150 성장·자동화·확장",
    "feature": "AI제안 센터",
    "salesforce": "중",
    "zendesk": "중",
    "intercom": "중",
    "onechat": "갭",
    "priority": "차별",
    "suggestion": "운영자에게 ‘무엇을 바꿀까’를 모아주는 전용 제안센터가 있으면 매우 강력합니다."
  }
];